# Simplified configuration for Railway
[build]
builder = "NIXPACKS"

[deploy]
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[environments.production.variables]
FLASK_ENV = "production"
# Updated to match your actual domain with www and HTTPS
BASE_URL = "https://www.carsona.in"
